name: junaya_voicechat_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  flutter_animate: ^4.5.2
  lucide_icons: ^0.257.0
  glassmorphism: ^3.0.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  country_flags: ^3.0.0
  flutter_svg: ^2.0.10+1
  provider: ^6.1.5+1
  shared_preferences: ^2.5.5
  image_picker: ^1.2.3
  socket_io_client: ^3.1.6


  cupertino_icons: ^1.0.8
  firebase_core: ^4.12.0
  firebase_auth: ^6.5.5
  cloud_firestore: ^6.7.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.6
  path: ^1.9.1
  permission_handler: ^13.0.0
  livekit_client: ^2.5.9
  dio: ^5.11.0
  flutter_secure_storage: ^11.0.0

  lottie: ^3.3.1
  rive: ^0.13.20
  video_player: ^2.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/logo.png

    # backgrounds
    - assets/backgrounds/

    # users
    - assets/users/

    # banners
    - assets/banners/

    # moments
    - assets/images/moments/

    # rooms
    - assets/rooms/
    - assets/categories/

    # gifts and animations
  #  - assets/gifts/
 #   - assets/animations/
 #   - assets/animations/gifts/
#    - assets/animations/entrance/
#    - assets/animations/vip/

    # icons
    - assets/icons/





  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

