// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNGu8tiAIaCOuk-6gqIlxX2hHKtKOk1so',
    appId: '1:865954546319:web:099db78b650845b81a26fa',
    messagingSenderId: '865954546319',
    projectId: 'junaid-7787',
    authDomain: 'junaid-7787.firebaseapp.com',
    storageBucket: 'junaid-7787.firebasestorage.app',
    measurementId: 'G-J95NLN2P95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGC4QOyELvJOGfTZlyVUnlM4fwwPxzEak',
    appId: '1:865954546319:android:a9b480e3251bc9f01a26fa',
    messagingSenderId: '865954546319',
    projectId: 'junaid-7787',
    storageBucket: 'junaid-7787.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqWNaSDAAZ8Qn3FK4paDbQeN9_KMoKtjw',
    appId: '1:865954546319:ios:8ef2de120e0c9e961a26fa',
    messagingSenderId: '865954546319',
    projectId: 'junaid-7787',
    storageBucket: 'junaid-7787.firebasestorage.app',
    iosBundleId: 'com.example.junayaVoicechatApp',
  );
}
